version: '3.4'
services:
  social-v2.clothes.admin:
    image: social-v2.clothes.admin
    container_name: social-v2.clothes.admin
    build:
      context: ./clients/Social-v2.Clothes.Admin
      dockerfile: Dockerfile
    ports:
      - 3111:3000
    restart: always

  storage-mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db
    networks:
      - mongo_net
    restart: always

  learning-chinese-video.storage-api:
    image: learning-chinese-video.storage-api
    container_name: learning-chinese-video.storage-api
    build:
      context: ./Services/LearningVideoStorageApi
      dockerfile: Dockerfile
    ports:
      - 2501:2501
    restart: always
    networks:
      - mongo_net

  social-v2.clothes.store-react:
    image: social-v2.clothes.store-react
    container_name: social-v2.clothes.store-react
    build:
      context: ./clients/Social-v2.Clothes.Store
      dockerfile: Dockerfile
    ports:
      - 1611:80
    restart: always

  social-v2.clothes.api-debug:
    image: social-v2.clothes.api-debug
    container_name: social-v2.clothes.api-debug
    build:
      context: ./services/Social-v2.Clothes.Api
      dockerfile: Social-v2.Clothes.Api/Dockerfile-debug
    ports:
      - 3954:80
    restart: always

  social-v2.clothes.api-production:
    image: social-v2.clothes.api-production
    container_name: social-v2.clothes.api-production
    build:
      context: ./services/Social-v2.Clothes.Api
      dockerfile: Social-v2.Clothes.Api/Dockerfile
    ports:
      - 3954:80
    restart: always

volumes:
  dbdata6:

networks:
  mongo_net:
    driver: bridge
