version: '3.4'
services:
  learning-chinese-video-fe:
    image: learning-chinese-video-fe
    container_name: learning-chinese-video-fe
    build:
      context: ./Clients/LearningChineseVideo
      dockerfile: Dockerfile
    ports:
      - 2401:3000
    restart: always 

  learning-chinese-video-storage-api:
    image: learning-chinese-video-storage-api
    container_name: learning-chinese-video-storage-api
    build:
      context: ./Services/LearningVideoStorageApi
      dockerfile: Dockerfile
    ports:
      - 2601:2601
    restart: always 

  learning-chinese-video-api:
    image: learning-chinese-video-api
    container_name: learning-chinese-video-api
    build:
      context: ./Services/LearningVideoApi
      dockerfile: Dockerfile
    ports:
      - 2501:80
    restart: always

  learning-chinese-video-api-staging:
    image: learning-chinese-video-api
    container_name: learning-chinese-video-api
    build:
      context: ./Services/LearningVideoApi
      dockerfile: Dockerfile-staging
    ports:
      - 2501:80
    restart: always 
  

